version: '3.8'

services:
  app:
    image: matskuman5/express-app:latest
    ports:
      - '8080:8080'
    labels:
      - 'com.centurylinklabs.watchtower.enable=true'
    container_name: app
  watchtower:
    image: containrrr/watchtower
    environment:
      - WATCHTOWER_POLL_INTERVAL=30
      - WATCHTOWER_LABEL_ENABLE=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower
